@startuml

package Data {
interface IEntity {
    + Id(): int
    + IsDestroyed(): bool
}

interface Entity1 {
    + property1: int
}

interface Entity2 {
    + property2: float
}
}

package System {
interface ISystem {
    + Execute(): void
}

class System1 {}
}

package Composition {
class LifeTimeScope {
    + Configure(builder: IContainerBuilder): void
}

class EntryPoint {
    + Initialize(): void
}
}

package Framework {
class Component1 {}

class Component2 {}
}

Data.Entity1 ..|> Data.IEntity
Data.Entity2 ..|> Data.IEntity

System.System1 ..|> System.ISystem
System.System1 ..> Data.Entity1
System.System1 ..> Data.Entity2

Framework.Component1 ..|> Data.Entity1
Framework.Component2 ..|> Data.Entity2

Composition.LifeTimeScope ..> System.System1
Composition.LifeTimeScope ..> Framework.Component1
Composition.LifeTimeScope ..> Framework.Component2

Composition.EntryPoint ..> System.System1

@enduml